import { Rotor } from './enigma';

/**
 *
 * @param chars the length all the characters in the rotor
 * @example 26 = abcdefghijklmnopqrstuvwxyz
 */
export const getRandomRotor = (chars = 26): Rotor => {
  const outputs = Array.from({ length: 26 }, (_, i) => i);
  const rotor: Rotor = {
    id: Date.now(),
    offset: 0,
    wires: [],
  };
  let input = 0;

  while (input !== chars) {
    const i = Math.floor(Math.random() * outputs.length);

    if (input === outputs[i]) continue;

    rotor.wires.push({
      input,
      output: outputs.splice(i, 1)[0],
    });

    input++;
  }

  return rotor;
};

/**
 * static rotor data
 */
export const getRotors = (): Rotor[] => [
  {
    id: 0,
    offset: 0,
    wires: [
      { input: 0, output: 2 },
      { input: 1, output: 5 },
      { input: 2, output: 7 },
      { input: 3, output: 20 },
      { input: 4, output: 19 },
      { input: 5, output: 3 },
      { input: 6, output: 8 },
      { input: 7, output: 22 },
      { input: 8, output: 15 },
      { input: 9, output: 0 },
      { input: 10, output: 17 },
      { input: 11, output: 14 },
      { input: 12, output: 4 },
      { input: 13, output: 25 },
      { input: 14, output: 1 },
      { input: 15, output: 6 },
      { input: 16, output: 10 },
      { input: 17, output: 24 },
      { input: 18, output: 16 },
      { input: 19, output: 11 },
      { input: 20, output: 18 },
      { input: 21, output: 13 },
      { input: 22, output: 12 },
      { input: 23, output: 21 },
      { input: 24, output: 23 },
      { input: 25, output: 9 },
    ],
  },
  {
    id: 1,
    offset: 0,
    wires: [
      { input: 0, output: 21 },
      { input: 1, output: 23 },
      { input: 2, output: 24 },
      { input: 3, output: 25 },
      { input: 4, output: 12 },
      { input: 5, output: 7 },
      { input: 6, output: 15 },
      { input: 7, output: 6 },
      { input: 8, output: 14 },
      { input: 9, output: 3 },
      { input: 10, output: 0 },
      { input: 11, output: 16 },
      { input: 12, output: 13 },
      { input: 13, output: 19 },
      { input: 14, output: 9 },
      { input: 15, output: 5 },
      { input: 16, output: 11 },
      { input: 17, output: 1 },
      { input: 18, output: 22 },
      { input: 19, output: 17 },
      { input: 20, output: 8 },
      { input: 21, output: 18 },
      { input: 22, output: 10 },
      { input: 23, output: 20 },
      { input: 24, output: 4 },
      { input: 25, output: 2 },
    ],
  },
  {
    id: 2,
    offset: 0,
    wires: [
      { input: 0, output: 18 },
      { input: 1, output: 3 },
      { input: 2, output: 5 },
      { input: 3, output: 17 },
      { input: 4, output: 6 },
      { input: 5, output: 21 },
      { input: 6, output: 10 },
      { input: 7, output: 12 },
      { input: 8, output: 23 },
      { input: 9, output: 11 },
      { input: 10, output: 15 },
      { input: 11, output: 22 },
      { input: 12, output: 13 },
      { input: 13, output: 2 },
      { input: 14, output: 7 },
      { input: 15, output: 14 },
      { input: 16, output: 8 },
      { input: 17, output: 0 },
      { input: 18, output: 16 },
      { input: 19, output: 4 },
      { input: 20, output: 1 },
      { input: 21, output: 19 },
      { input: 22, output: 9 },
      { input: 23, output: 20 },
      { input: 24, output: 25 },
      { input: 25, output: 24 },
    ],
  },
  {
    id: 3,
    offset: 0,
    wires: [
      { input: 0, output: 2 },
      { input: 1, output: 3 },
      { input: 2, output: 23 },
      { input: 3, output: 17 },
      { input: 4, output: 7 },
      { input: 5, output: 11 },
      { input: 6, output: 14 },
      { input: 7, output: 6 },
      { input: 8, output: 15 },
      { input: 9, output: 13 },
      { input: 10, output: 21 },
      { input: 11, output: 22 },
      { input: 12, output: 25 },
      { input: 13, output: 16 },
      { input: 14, output: 0 },
      { input: 15, output: 18 },
      { input: 16, output: 9 },
      { input: 17, output: 12 },
      { input: 18, output: 20 },
      { input: 19, output: 10 },
      { input: 20, output: 24 },
      { input: 21, output: 19 },
      { input: 22, output: 4 },
      { input: 23, output: 5 },
      { input: 24, output: 1 },
      { input: 25, output: 8 },
    ],
  },
  {
    id: 4,
    offset: 0,
    wires: [
      { input: 0, output: 7 },
      { input: 1, output: 21 },
      { input: 2, output: 25 },
      { input: 3, output: 0 },
      { input: 4, output: 17 },
      { input: 5, output: 16 },
      { input: 6, output: 20 },
      { input: 7, output: 22 },
      { input: 8, output: 4 },
      { input: 9, output: 19 },
      { input: 10, output: 2 },
      { input: 11, output: 14 },
      { input: 12, output: 11 },
      { input: 13, output: 24 },
      { input: 14, output: 18 },
      { input: 15, output: 10 },
      { input: 16, output: 15 },
      { input: 17, output: 12 },
      { input: 18, output: 23 },
      { input: 19, output: 3 },
      { input: 20, output: 5 },
      { input: 21, output: 13 },
      { input: 22, output: 9 },
      { input: 23, output: 1 },
      { input: 24, output: 8 },
      { input: 25, output: 6 },
    ],
  },
  {
    id: 5,
    offset: 0,
    wires: [
      { input: 0, output: 2 },
      { input: 1, output: 12 },
      { input: 2, output: 0 },
      { input: 3, output: 20 },
      { input: 4, output: 18 },
      { input: 5, output: 19 },
      { input: 6, output: 7 },
      { input: 7, output: 14 },
      { input: 8, output: 13 },
      { input: 9, output: 22 },
      { input: 10, output: 8 },
      { input: 11, output: 3 },
      { input: 12, output: 1 },
      { input: 13, output: 21 },
      { input: 14, output: 15 },
      { input: 15, output: 6 },
      { input: 16, output: 24 },
      { input: 17, output: 10 },
      { input: 18, output: 4 },
      { input: 19, output: 16 },
      { input: 20, output: 25 },
      { input: 21, output: 17 },
      { input: 22, output: 9 },
      { input: 23, output: 5 },
      { input: 24, output: 11 },
      { input: 25, output: 23 },
    ],
  },
  {
    id: 6,
    offset: 0,
    wires: [
      { input: 0, output: 1 },
      { input: 1, output: 15 },
      { input: 2, output: 8 },
      { input: 3, output: 13 },
      { input: 4, output: 10 },
      { input: 5, output: 3 },
      { input: 6, output: 11 },
      { input: 7, output: 21 },
      { input: 8, output: 18 },
      { input: 9, output: 5 },
      { input: 10, output: 2 },
      { input: 11, output: 0 },
      { input: 12, output: 14 },
      { input: 13, output: 20 },
      { input: 14, output: 9 },
      { input: 15, output: 4 },
      { input: 16, output: 24 },
      { input: 17, output: 22 },
      { input: 18, output: 23 },
      { input: 19, output: 25 },
      { input: 20, output: 7 },
      { input: 21, output: 6 },
      { input: 22, output: 19 },
      { input: 23, output: 16 },
      { input: 24, output: 17 },
      { input: 25, output: 12 },
    ],
  },
  {
    id: 7,
    offset: 0,
    wires: [
      { input: 0, output: 24 },
      { input: 1, output: 19 },
      { input: 2, output: 25 },
      { input: 3, output: 11 },
      { input: 4, output: 20 },
      { input: 5, output: 4 },
      { input: 6, output: 3 },
      { input: 7, output: 8 },
      { input: 8, output: 2 },
      { input: 9, output: 7 },
      { input: 10, output: 18 },
      { input: 11, output: 9 },
      { input: 12, output: 23 },
      { input: 13, output: 12 },
      { input: 14, output: 10 },
      { input: 15, output: 6 },
      { input: 16, output: 17 },
      { input: 17, output: 16 },
      { input: 18, output: 0 },
      { input: 19, output: 1 },
      { input: 20, output: 14 },
      { input: 21, output: 15 },
      { input: 22, output: 5 },
      { input: 23, output: 13 },
      { input: 24, output: 21 },
      { input: 25, output: 22 },
    ],
  },
  {
    id: 8,
    offset: 0,
    wires: [
      { input: 0, output: 12 },
      { input: 1, output: 20 },
      { input: 2, output: 18 },
      { input: 3, output: 25 },
      { input: 4, output: 11 },
      { input: 5, output: 17 },
      { input: 6, output: 23 },
      { input: 7, output: 14 },
      { input: 8, output: 0 },
      { input: 9, output: 3 },
      { input: 10, output: 19 },
      { input: 11, output: 21 },
      { input: 12, output: 13 },
      { input: 13, output: 6 },
      { input: 14, output: 8 },
      { input: 15, output: 10 },
      { input: 16, output: 1 },
      { input: 17, output: 16 },
      { input: 18, output: 2 },
      { input: 19, output: 24 },
      { input: 20, output: 9 },
      { input: 21, output: 22 },
      { input: 22, output: 5 },
      { input: 23, output: 15 },
      { input: 24, output: 4 },
      { input: 25, output: 7 },
    ],
  },
  {
    id: 9,
    offset: 0,
    wires: [
      { input: 0, output: 5 },
      { input: 1, output: 2 },
      { input: 2, output: 18 },
      { input: 3, output: 23 },
      { input: 4, output: 8 },
      { input: 5, output: 16 },
      { input: 6, output: 13 },
      { input: 7, output: 0 },
      { input: 8, output: 7 },
      { input: 9, output: 19 },
      { input: 10, output: 20 },
      { input: 11, output: 15 },
      { input: 12, output: 22 },
      { input: 13, output: 17 },
      { input: 14, output: 9 },
      { input: 15, output: 3 },
      { input: 16, output: 6 },
      { input: 17, output: 14 },
      { input: 18, output: 21 },
      { input: 19, output: 10 },
      { input: 20, output: 1 },
      { input: 21, output: 12 },
      { input: 22, output: 11 },
      { input: 23, output: 4 },
      { input: 24, output: 25 },
      { input: 25, output: 24 },
    ],
  },
];
